branch-defaults:
  default:
    environment: <ENV>
global:
  application_name: <APP>
  default_region: eu-west-1
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1
  sc: null
