branch-defaults:
  default:
    environment: <ENV>
global:
  application_name: <APP>
  default_region: eu-west-2
  default_platform: 64bit Amazon Linux 2016.09 v2.3.0 running Docker 1.11.2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
